/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary:                      '#3525cd',
        'primary-container':          '#4f46e5',
        'primary-fixed':              '#e2dfff',
        'primary-fixed-dim':          '#c3c0ff',
        'on-primary':                 '#ffffff',
        'on-primary-fixed':           '#0f0069',
        'on-primary-fixed-variant':   '#3323cc',
        'on-primary-container':       '#dad7ff',
        secondary:                    '#58579b',
        'secondary-container':        '#b6b4ff',
        'secondary-fixed':            '#e2dfff',
        'secondary-fixed-dim':        '#c3c0ff',
        'on-secondary':               '#ffffff',
        'on-secondary-container':     '#454386',
        'on-secondary-fixed':         '#140f54',
        'on-secondary-fixed-variant': '#413f82',
        tertiary:                     '#7e3000',
        'tertiary-container':         '#a44100',
        'tertiary-fixed':             '#ffdbcc',
        'tertiary-fixed-dim':         '#ffb695',
        'on-tertiary':                '#ffffff',
        'on-tertiary-container':      '#ffd2be',
        'on-tertiary-fixed':          '#351000',
        'on-tertiary-fixed-variant':  '#7b2f00',
        error:                        '#ba1a1a',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'on-error-container':         '#93000a',
        surface:                      '#f8f9fa',
        'surface-dim':                '#d9dadb',
        'surface-bright':             '#f8f9fa',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f3f4f5',
        'surface-container':          '#edeeef',
        'surface-container-high':     '#e7e8e9',
        'surface-container-highest':  '#e1e3e4',
        'surface-variant':            '#e1e3e4',
        'surface-tint':               '#4d44e3',
        'on-surface':                 '#191c1d',
        'on-surface-variant':         '#464555',
        'inverse-surface':            '#2e3132',
        'inverse-on-surface':         '#f0f1f2',
        'inverse-primary':            '#c3c0ff',
        outline:                      '#777587',
        'outline-variant':            '#c7c4d8',
        background:                   '#f8f9fa',
        'on-background':              '#191c1d',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
}
